version = 1.0

[default.deploy.parameters]
stack_name              = "wh-zendesk-trans-dev"
s3_bucket               = "your-artifactory-bucket-dev"
s3_prefix               = "lambda/zendesk-translate-eventbridge-webhook-dev"
region                  = "eu-west-1"
capabilities            = "CAPABILITY_NAMED_IAM"
tags                    = "project=\"zendesk-translation\" owner=\"Customer service\" environment=\"dev\""
fail_on_empty_changeset = false
parameter_overrides = [
	"Environment=dev",
	"DebugParam=true",
	"ZendeskKeySSMParameterPath=/config/zendesk-translation/zendesk_api_key",
	"ZendeskUsernameMail=zendesk-api-user-dev@domain.com",
	"ZendeskSubdomain=zendesk-subdomain",
	"ZendeskTicketLangFieldId=<ticketfield_id>",
	"KmsKeyId=kms_key_id_to_protect_ssm_parameters",
	"EventBusName=customer-eventbus-dev",
	"BasicAuthUsernameSSMParameterPath=/config/zendesk-translation/basicauth_username",
	"BasicAuthPasswordSSMParameterPath=/config/zendesk-translation/basicauth_password",
	"EventBusName=customer-eventbus-dev"
]

[production]
[production.deploy]
[production.deploy.parameters]
stack_name              = "wh-zendesk-trans"
s3_bucket               = "your-artifactory-bucket-dev"
s3_prefix               = "lambda/zendesk-translate-eventbridge-webhook"
capabilities            = "CAPABILITY_NAMED_IAM"
region                  = "eu-west-1"
fail_on_empty_changeset = false
tags                    = "project=\"zendesk-translation\" owner=\"Customer service\" environment=\"prod\""
parameter_overrides = [
	"Environment=prod",
	"DebugParam=true",
	"ZendeskKeySSMParameterPath=/config/zendesk-translation/zendesk_api_key",
	"ZendeskUsernameMail=zendesk-api-user-dev@domain.com",
	"ZendeskSubdomain=zendesk-subdomain",
	"ZendeskTicketLangFieldId=<ticketfield_id>",
	"KmsKeyId=kms_key_id_to_protect_ssm_parameters",
	"BasicAuthUsernameSSMParameterPath=/config/zendesk-translation/basicauth_username",
	"BasicAuthPasswordSSMParameterPath=/config/zendesk-translation/basicauth_password",
	"EventBusName=customer-eventbus-prod"
]
